apisite/urls.py
from django.urls import path, include
from .views import *
from .api_service import *

urlpatterns = [
    path('auth/', include('rest_auth.urls')),
    path('inventario/<int:pk>/', InventarioDetails.as_view(), name='Inventario do usuário'),
    path('inventario/items/<int:pk>/', item_usuario, name="Items do usuário"),
    path('inventario/<int:pk>/<int:item>/', InventarioUpdate.as_view(), name="Atualizar inventario")
]

appsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('apisite.urls')),
    path('', include('website.urls')),
    path('marketplace/', include(('transacaosite.urls','transacaosite'), namespace='transacaosite'))
]

transacaosite/urls.py
from django.urls import path
from .views import *
from .pagamento_boleto import paid_boleto, get_data_from_boleto
from apisite.api_service import transaction_filter

'''
json do cart
capturar o json do javascript e fazer get no front
'''
urlpatterns = [
    path('add_item/', add_item_cart, name='add_item'),
    path('list_item/', list_items, name='list_items'),
    path('update_item_cart/<int:id>/<int:new_quantity>/', update_cart_same_item, name='update_items'),
    path('delete/', delete_cart, name='delete'),
    path('generate_boleto/', generate_boleto, name='generate_boleto'),
    path('create_boleto/', request_boleto, name='request_boleto'),
    path('paid_boleto/', paid_boleto, name='paid_boleto'),
    path('delete_item/<int:id>/', delete_item, name='delete_item'),
    path('get_transaction/', get_data_from_boleto, name='boleto_await'),
    path('filter/', transaction_filter, name="Filtrar transacoes"),
]

website/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', home, name='Home'),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name='login_site'),
    path('cadastro/', signup, name='signup_site'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout_site'),
    path('perfil/<int:id_user>/', perfil, name='inventario_user'),
    path('marketplace/', home_marketplace, name='marketplace_site'),
    path('marketplace/boleto/', boleto_marketplace, name='boleto_final'),
    path('marketplace/cart/', cart_marketplace, name='marketplace_cart'),
    path('relatorios/', relatorio_transaction, name='relatorio_transaction')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, label="Primeiro nome", required=True, help_text='Obrigatório')
    last_name = forms.CharField(max_length=30, label="Ultimo nome", required=True, help_text='Obrigatório')
    email = forms.EmailField(max_length=254, help_text='Obrigatório')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

website/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from .forms import *
from transacaosite.models import *
from django.urls import reverse

def home(request):
    if request.user.is_authenticated:
        return render(request, 'index.html')
    return render(request, 'index.html')


def signup(request):
    if request.user.is_authenticated:
        return redirect('inventario_user', id_user=request.user.pk)
    else:
        form = SignUpForm(request.POST or None)
        if request.method == 'POST':
            if form.is_valid():
                user = form.save()
                user.refresh_from_db()
                form.save()
                return redirect('login_site')
            else:
                form = SignUpForm(request.POST or None)
        return render(request, 'signup.html', {'form': form})


def perfil(request, id_user):
    data_items = []
    try:        
        inventario = Inventario.objects.get(id=id_user)
        inventario_game = InventarioItemGame.objects.filter(usuario=inventario, quantidade__gt=0)
        for dados in inventario_game:
            item = Item.objects.get(id_item=dados.item_id)
            data_items.append({
                'item_nome':item,
                'item_quantidade':dados.quantidade,
                'item_img': item.imagem_item
            })
        perfil = Inventario.objects.filter(id=id_user)
        boleto = Transacao.objects.filter(usuario_transacao=inventario).last()
        data_items.reverse()
    except:
        return redirect(home)
    return render(request, 'perfil.html', {'dados': perfil,'items':data_items, 'boletos':boleto})


def home_marketplace(request):
    items_estoque = []
    try:
        items = Item.objects.all()
        for item in items:
            items_estoque.append({
                'item_nome':item.nome_item,
                'item_preco':item.valor_item,
                'item_id': item.id_item,
                'item_img':item.imagem_item
            })
        items_estoque.reverse()
    except:
        items_estoque = None
    return render(request, 'marketplace.html', {'items':items_estoque})

def boleto_marketplace(request):
    boletos_aprovados = []
    boletos_a_pagar = []
    try:
        usuario = Inventario.objects.get(id=request.user.pk)
        for data in Transacao.objects.filter(usuario_transacao=usuario, status_boleto=True)[:]:
            boletos_aprovados.append(data)
        for data in Transacao.objects.filter(usuario_transacao=usuario, status_boleto=False):
            boletos_a_pagar.append(data)
        boletos_aprovados.reverse()
    except:
        boletos = None
    return render(request, 'boleto_wait.html', {'boletos_ok' : boletos_aprovados[:4],
                                                'boletos_a_pagar' : boletos_a_pagar})

def cart_marketplace(request):
    return render(request, 'marketplace_cart.html')

def relatorio_transaction(request):
    return render(request, 'relatorios.html')

website/templates/boleto_wait.html
{% extends "layout/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/boleto.css' %}"/>
{% endblock %}

{% block title %}
    Boletos/Transações
{% endblock%}

{% block content %}
{% if user.is_authenticated %}
<section class="boletos">
        <span class="titulo-inventario">
                <h1 class="plaquinha">Boletos</h1>
        </span>
    <div class="transaction-boleto">
    <div class="boleto-aguarda">
        <h1>Boleto pendente:</h1>
        <div class="boleto-aguardando">
        {% if boletos_a_pagar %}

                {% for boleto in boletos_a_pagar %}
                    <table class="cada-boleto">
                        <thead>
                            <th>Descrição</th>
                            <th>Informação</th>
                        </thead>
                    <tbody>
                        <tr>
                                <td>Código da transação:</td>
                                <td> {{ boleto.codigo_boleto }}</td>
                        </tr>
                        <tr>
                                <td>Código do documento:</td>
                                <td>123456 78910111213 1415</td>
                        </tr>
                        <tr>
                                <td>Valor do documento:</td>
                                <td>R$<span class="valor-boleto">{{ boleto.valor_boleto }}</span></td>
                        </tr>
                        <tr>
                                <td>Status do boleto:</td>
                                <td style="color:red; font-weight:bolder">Aguardando Pagamento</td>
                        </tr>
                        <tr>
                            <td>Data do documento:</td>
                            <td>{{ boleto.data_boleto_criado }}</td>
                        </tr>
                        <tr>
                            <td>Vencimento:</td>
                            <td>{{ boleto.expiration_boleto_date }}</td>
                        </tr>
                        <input type="hidden" value="{{request.user.first_name}} {{ request.user.last_name}}" />
                        <input type="hidden" value="{{request.user.email}}" />
                    </tbody>
                    </table>
                {% endfor %}
                <img src='http://127.0.0.1:8000/static/assets/boletocodigo.jpg' class="codigo_fiscal" width="350"/>
                <button class="print-boleto">Imprimir boleto</button>
            {% else %}
            <p><b>Ufa! Nenhum boleto aguardando pagamento!</b><br><a href="{% url "marketplace_site" %}">Compre agora!</a></p>
        {% endif %}
        </div>
        
    </div>
        <div class="boletos-pagos">
            <h1 class="titulo-aprovado">Ultimos boletos pagos:</h1>
            {% if boletos_ok %}
                {% for boleto in boletos_ok %}
                    <div class="boleto-aprovado">
                        <p>Código do boleto: {{ boleto.codigo_boleto }}</p>
                        <p style="color:green">Status do boleto: <b>Boleto Pago</b></p>
                        <p>Gerado em {{ boleto.data_boleto_criado }}</p>
                    </div>
                {% endfor %}
            </div>
        {% else %}
        <h1>Nenhuma compra efetuada</h1>
    {% endif %}
{% else %}
    <div class="warning">
        <span class="omg-warning"></span>
        <div class="warning-inside">
            <h1>Você não está logado!</h1>
        </div> 
    </div>
{% endif %}
</div>
</section>
<script type="text/javascript" src="{% static 'js/print_boleto.js' %}"></script>
{% endblock %}

website/templates/index.html
{% extends "layout/base.html" %}

{% block title %}
    Collita Game - Homepage
{% endblock%}

{% block content %}
    {% if user.is_authenticated %}
        <h1>
            Bem vindo {{ request.user }} !
        </h1>
        <div class="base-homepage">
            <ul>
                <li><p>E-commerce e inventário para o jogo Collita!</p></li>
                <li>
                    <a href="{% url 'inventario_user' user.id %}">Seu inventário</a>
                </li>
                <li>
                    <a href="{% url 'marketplace_site' %}">Nosso marketplace para melhorar seu jogo!</a>
                </li>
                <li>
                    <a href="{% url 'boleto_final' %}">Seus boletos pagos, ou pendentes!</a>
                </li>
            </ul>
        </div>
        {% else %}
        <section>
            <div class="base-homepage">
                <h1 style="text-align:center">MageHut Games apresenta Collita!</h1>
                <a href="{{STATIC_URL}}/static/assets/GAME_COLLITA.7z"><button class="download-game">Baixe o Game Agora!</button></a>
                <div class="sub-homepage">
                    <p>O jogo 2D que virou febre no mundo todo!</p>
                    <img src="{{STATIC_URL}}/static/assets/caozinho.png/" width="400" style="margin:0 auto"/>
                </div>
            </div>
        </section>
    {% endif %}

{% endblock %}

website/templates/login.html
{% extends "layout/base.html"%}

{% block title %}
    Login
{% endblock%}

{% block content %}
    {% if user.is_authenticated %}
    <div class="warning">
     <div class="warning-inside">
        <p>Você está autenticado não precisa se logar</p>
            <br>
            <a href="{% url 'inventario_user' user.pk  %}"/>Voltar ao perfil</a>
     </div>
    </div>
    {% else %}
    <div class="form-group">
        <span class="titulo-inventario">
                <h1 class="plaquinha">Login</h1>
            </span>
        <form method='POST'>
            <ul class="form-login">
                {% csrf_token %}
                {{ form.as_ul }}
            </ul>
            <button type="submit">Login</button>
        </form>
    </div>        
    {% endif %}
{% endblock %}

website/templates/marketplace.html
{% extends "layout/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/marketplace.css' %}"/>
{% endblock css %}

{% block title %}
    Marketplace
{% endblock%}

{% block content %}
{% if user.is_authenticated %}   
<div class="marketplace">
    <span class="titulo-inventario">
            <h1 class="plaquinha">Markeplace</h1>
    </span>
    <div class="marketplace-items">
    {% if error %}
    <div class="warning">
        <span class="omg-warning"></span>
        <div class="warning-inside">
                <p class="error">{{ error }}</p>
                <a href="/marketplace">Volte para o marketplace</a><br>
                <a href="{% url 'boleto_final' %}">Verifique seus boletos</a>
        </div>
    </div>
    {% endif %}
    {% if not error %}
        {% if items %}
                {% for item in items %}
                    <div class="item-marketplace">
                        <input type="hidden" name="id_item" value="{{item.item_id}}">
                        <div class="item-titulo">
                            <p>{{ item.item_nome }}</p>
                        </div>
                        <p class="item-preco">{{ item.item_preco }}</p>
                        <img src="{{STATIC_URL}}/media/{{ item.item_img }}" alt="{{ item.item_nome }}" width="80"/>
                        <input type="number" class="quantidade" min="1" max="100" value="1">
                        <button class="comprar"><span class="cart-market"></span></button>
                    </div>
                {% endfor %}
                <aside class="my-cart">
                    <b style="position:fixed; top:125px;">Historico de compra:</b>
                            <table>
                                <tbody class="cart-list">
                
                                </tbody>
                            </table>
                            <div class="total-market">
                            </div>
                            <a href="{% url 'transacaosite:generate_boleto' %}"><button class="finaliza-cart">Gerar Boleto</button></a>
                            <button class="remove-itens">Limpar Carrinho</button>
                </aside>
        {% else %}
            <div class="warning">
                <h1>Nenhum item para compra</h1>
            </div>
        {% endif %}
        {% else %}
        <br>
    {% endif %}
    </div>
    </div>
    <script type="text/javascript" src="{% static 'js/list_cart.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/add_cart.js' %}"></script>
    {% else %}
    <div class="warning">
            <span class="omg-warning"></span>
            <div class="warning-inside">
                <h1>Você não está logado!</h1>
            </div> 
        </div>
    {% endif %}
{% endblock content %}

website/templates/marketplace_cart.html
{% extends "layout/base.html"%}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/cart-market.css' %}">
{% endblock %}

{% block title %}
    Carrinho
{% endblock%}

{% block content %}
    <section class="carrinho">
            <span class="titulo-inventario">
                    <h1 class="plaquinha">Carrinho</h1>
            </span>
    <h1 class="none-cart"></h1>
        <table class="cart-market">
                <thead style="font-weight:bolder">
                    <tr>
                        <td>
                            Id do pedido
                        </td>
                        <td>
                            Nome do item
                        </td>
                        <td>
                            Preço do item
                        </td>
                        <td>
                            Quantidade do Item
                        </td>
                        <td>
                            Excluir Item
                        </td>
                    </tr>
                    </thead>
            <tbody class="carrinho-main">

            </tbody>
            <tfoot class="valor-total">

            </tfoot>
        </table>
    </section>
<script type="text/javascript" src="{% static 'js/main_cart_list.js' %}"></script>
{% endblock content %}

website/templates/perfil.html
{% extends "layout/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/perfil.css' %}"/>
{% endblock css %}

{% block title %}
    {% for dado in dados %}
    Jogador {{dado.usuario}}
    {% endfor %}
{% endblock%}

{% block content %}

<div class="perfil-usuario">
        <span class="titulo-inventario">
                <h1 class="plaquinha">Perfil do usuário</h1>
        </span>
        <div class="dados-usuario">
            <div class="info-usuario">
                {% for dado in dados %}
                    <ul>
                        <li><b>Username</b>: {{ dado.usuario }}</li>
                        <li><b>Nome do jogador</b>: {{dado.usuario.first_name}} {{dado.usuario.last_name}}</li>
                        <li><b>E-mail</b>: {{dado.usuario.email}} </li>
                    </ul>
                {% endfor %}
            </div>
            <div class="boletos-usuario">
                <p style="text-align: center"><b>Ultimo boleto:</b></p>
                {% if boletos %}
                    <p><b>Código boleto</b>: {{ boletos.codigo_boleto }}</p>
                    <p><b>Status</b>: <span class="status-boleto">{{ boletos.status_boleto }}</span></p>
                    {% if boletos.status_boleto is False %}
                        <p><b>Prazo do pagamento</b>: {{ boletos.expiration_boleto_date }}</p>
                    {% endif%}
                    <a href="{% url 'boleto_final' %}" style="float:right; font-weight:bold">Todos os boletos</a>
                {% else %}
                    <p style="font-weight: bolder">Nenhum boleto encontrado D:</p>
                {% endif %}
            </div>
        </div>
    <div class="inventario-usuario">
        <span class="titulo-inventario">
            <h1 class="plaquinha">Inventário In-Game</h1>
        </span>
            {% if items %}
                {% for item in items %}
                    <section class="item-inventario">
                        <img src="http://127.0.0.1:8000/media/{{ item.item_img }}" alt="{{item.item_nome}}"/>
                            <div class="nome-powerup">
                                <b>Power-up: {{item.item_nome}}</b>
                            </div>
                        <b>Qtd:</b> x {{item.item_quantidade}}
                    </section>
                {% endfor %}
            {% else %}
                <p>Nenhum power up comprado</p>
            {% endif %}
    </div>
</div>
<script type="text/javascript" src="{% static 'js/profile.js' %}"></script>
{% endblock content %}

website/templates/relatorios.html
{% extends "layout/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/relatorios.css' %}"/>
{% endblock css %}


{% block content %}
{% if user.is_superuser %}
<section class="relatorio-gerencial">
    <div class="relatorio-filter" style="margin-top:25px;">
        <label for="mes-ano" style="font-weight: bolder">Mês e ano: </label><input type="month" min="2019-01" required>
        <label for="quantidade" style="font-weight: bolder">Quantidade de transações: </label>
        <input type="number" min="1" max="6" class="qtd" value="6" class="qtd-relatorios" style="width:30px" placeholder="quantidade">
        <label for="boleto-pago" style="font-weight: bolder">Exibir boleto pago:</label><input type="checkbox" class="boleto-check" checked="true"><br>
        <label for="username" style="font-weight: bolder">Nome do usuario: </label><input type="text" class="username" placeholder="Digite usuário especifico">
        <button style="width:100%" class="get-relatorio">Filtrar Transações</button>
    </div>
    <section class="root-relatorio" style="background:white"></section>
</section>

<script type="text/javascript" src="{% static 'js/relatorio_transaction.js' %}"></script>
{% else %}

<div class="warning">
    <span class="omg-warning"></span>
        <div class="warning-inside">Oooops!! Você não pode entrar aqui!<br><br><a href="/">Volte para a pagina principal!</a></div>
</div>

{% endif %}
{% endblock content %}

website/templates/signup.html
{% extends "layout/base.html"%}

{% block content %}

{% if user.is_authenticated %}
    <div class="warning">
        <div class="warning-inside">
            <p>Você já está logado!</p>
        </div>
    </div>
{% else %}
    <div class="form-group">
            <span class="titulo-inventario">
                <h1 class="plaquinha">Cadastro</h1>
            </span>
        <ul class="form-login">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_ul }}
                <button type="submit">Cadastro</button>
            </form>
        </ul>
    </div>
{% endif %}
{%endblock%}